flatpak install -y flathub org.kde.konsole
flatpak install -y flathub org.kde.yakuake
flatpak install -y flathub org.mozilla.firefox
flatpak install -y flathub com.google.Chrome
flatpak install -y flathub org.libreoffice.LibreOffice
flatpak install -y flathub org.kde.kwrite
flatpak install -y flathub org.kde.kate
flatpak install -y flathub net.lutris.Lutris
flatpak install -y flathub com.heroicgameslauncher.hgl
flatpak install -y flathub org.gimp.GIMP
flatpak install -y flathub org.kde.krita
flatpak install -y flathub org.inkscape.Inkscape
flatpak install -y flathub to.us.scrollprotocol.Profectus
flatpak install -y flathub org.kde.ark
flatpak install -y flathub org.kde.ktorrent
flatpak install -y flathub org.kde.krdc
flatpak install -y flathub org.mozilla.Thunderbird
flatpak install -y flathub org.kde.kalk
flatpak install -y flathub org.kde.ghostwriter
